config/routes.rb
Snmpcatcher::Application.routes.draw do
  resources :devices

  resources :trafficdata

  

end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/models/traffic_data.rb
class TrafficData < ActiveRecord::Base
end

app/models/trafficdatum.rb
class Trafficdatum < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :hostname, :ip, :snmpcommunity, :commentar, :password, :location)
    end
end

app/controllers/snmpcatcher_controller.rb
class SnmpcatcherController < ApplicationController
  def create
    device = Device.find(1)
    ifTable_columns = ["ifIndex", "ifDescr", "ifInOctets", "ifOutOctets"]
      SNMP::Manager.open(:Host => #{device.ip} , :Community => #{device.snmpcommunity}) do |manager|
        manager.walk(ifTable_columns) do |index, descr, inoctets, outoctets|
        trafficdata = Trafficdata.create(switchID = #{device.id}, ifIndex='#{index.value}', ifDescr='#{descr.value}', ifInOctets='#{inoctets.value}', ifOutOctets='#{outoctets.value}')
      end
    end
  end
end

app/controllers/trafficdata_controller.rb
class TrafficdataController < ApplicationController
  before_action :set_trafficdatum, only: [:show, :edit, :update, :destroy]

  # GET /trafficdata
  # GET /trafficdata.json
  def index
    @trafficdata = Trafficdatum.all
  end

  # GET /trafficdata/1
  # GET /trafficdata/1.json
  def show
  end

  # GET /trafficdata/new
  def new
    @trafficdatum = Trafficdatum.new
  end

  # GET /trafficdata/1/edit
  def edit
  end

  # POST /trafficdata
  # POST /trafficdata.json
  def create
    @trafficdatum = Trafficdatum.new(trafficdatum_params)

    respond_to do |format|
      if @trafficdatum.save
        format.html { redirect_to @trafficdatum, notice: 'Trafficdatum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trafficdatum }
      else
        format.html { render action: 'new' }
        format.json { render json: @trafficdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trafficdata/1
  # PATCH/PUT /trafficdata/1.json
  def update
    respond_to do |format|
      if @trafficdatum.update(trafficdatum_params)
        format.html { redirect_to @trafficdatum, notice: 'Trafficdatum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trafficdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trafficdata/1
  # DELETE /trafficdata/1.json
  def destroy
    @trafficdatum.destroy
    respond_to do |format|
      format.html { redirect_to trafficdata_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trafficdatum
      @trafficdatum = Trafficdatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trafficdatum_params
      params.require(:trafficdatum).permit(:switchID, :ifIndex, :ifDescr, :ifInOctets, :ifOutOctets, :diffInOctets, :diffOutOctets)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/trafficdata_helper.rb
module TrafficdataHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hostname %><br>
    <%= f.text_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :snmpcommunity %><br>
    <%= f.text_field :snmpcommunity %>
  </div>
  <div class="field">
    <%= f.label :commentar %><br>
    <%= f.text_area :commentar %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hostname</th>
      <th>Ip</th>
      <th>Snmpcommunity</th>
      <th>Commentar</th>
      <th>Password</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.hostname %></td>
        <td><%= device.ip %></td>
        <td><%= device.snmpcommunity %></td>
        <td><%= device.commentar %></td>
        <td><%= device.password %></td>
        <td><%= device.location %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Hostname:</strong>
  <%= @device.hostname %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @device.ip %>
</p>

<p>
  <strong>Snmpcommunity:</strong>
  <%= @device.snmpcommunity %>
</p>

<p>
  <strong>Commentar:</strong>
  <%= @device.commentar %>
</p>

<p>
  <strong>Password:</strong>
  <%= @device.password %>
</p>

<p>
  <strong>Location:</strong>
  <%= @device.location %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snmpcatcher</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snmpcatcher/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hostname %><br>
    <%= f.text_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :snmpcommunity %><br>
    <%= f.text_field :snmpcommunity %>
  </div>
  <div class="field">
    <%= f.label :commentar %><br>
    <%= f.text_area :commentar %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snmpcatcher/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/snmpcatcher/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hostname</th>
      <th>Ip</th>
      <th>Snmpcommunity</th>
      <th>Commentar</th>
      <th>Password</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.hostname %></td>
        <td><%= device.ip %></td>
        <td><%= device.snmpcommunity %></td>
        <td><%= device.commentar %></td>
        <td><%= device.password %></td>
        <td><%= device.location %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/snmpcatcher/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/snmpcatcher/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Hostname:</strong>
  <%= @device.hostname %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @device.ip %>
</p>

<p>
  <strong>Snmpcommunity:</strong>
  <%= @device.snmpcommunity %>
</p>

<p>
  <strong>Commentar:</strong>
  <%= @device.commentar %>
</p>

<p>
  <strong>Password:</strong>
  <%= @device.password %>
</p>

<p>
  <strong>Location:</strong>
  <%= @device.location %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/trafficdata/_form.html.erb
<%= form_for(@trafficdatum) do |f| %>
  <% if @trafficdatum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trafficdatum.errors.count, "error") %> prohibited this trafficdatum from being saved:</h2>

      <ul>
      <% @trafficdatum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :switchID %><br>
    <%= f.number_field :switchID %>
  </div>
  <div class="field">
    <%= f.label :ifIndex %><br>
    <%= f.text_field :ifIndex %>
  </div>
  <div class="field">
    <%= f.label :ifDescr %><br>
    <%= f.text_field :ifDescr %>
  </div>
  <div class="field">
    <%= f.label :ifInOctets %><br>
    <%= f.number_field :ifInOctets %>
  </div>
  <div class="field">
    <%= f.label :ifOutOctets %><br>
    <%= f.number_field :ifOutOctets %>
  </div>
  <div class="field">
    <%= f.label :diffInOctets %><br>
    <%= f.number_field :diffInOctets %>
  </div>
  <div class="field">
    <%= f.label :diffOutOctets %><br>
    <%= f.number_field :diffOutOctets %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trafficdata/edit.html.erb
<h1>Editing trafficdatum</h1>

<%= render 'form' %>

<%= link_to 'Show', @trafficdatum %> |
<%= link_to 'Back', trafficdata_path %>

app/views/trafficdata/index.html.erb
<h1>Listing trafficdata</h1>

<table>
  <thead>
    <tr>
      <th>Switchid</th>
      <th>Ifindex</th>
      <th>Ifdescr</th>
      <th>Ifinoctets</th>
      <th>Ifoutoctets</th>
      <th>Diffinoctets</th>
      <th>Diffoutoctets</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trafficdata.each do |trafficdatum| %>
      <tr>
        <td><%= trafficdatum.switchID %></td>
        <td><%= trafficdatum.ifIndex %></td>
        <td><%= trafficdatum.ifDescr %></td>
        <td><%= trafficdatum.ifInOctets %></td>
        <td><%= trafficdatum.ifOutOctets %></td>
        <td><%= trafficdatum.diffInOctets %></td>
        <td><%= trafficdatum.diffOutOctets %></td>
        <td><%= link_to 'Show', trafficdatum %></td>
        <td><%= link_to 'Edit', edit_trafficdatum_path(trafficdatum) %></td>
        <td><%= link_to 'Destroy', trafficdatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trafficdatum', new_trafficdatum_path %>

app/views/trafficdata/new.html.erb
<h1>New trafficdatum</h1>

<%= render 'form' %>

<%= link_to 'Back', trafficdata_path %>

app/views/trafficdata/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Switchid:</strong>
  <%= @trafficdatum.switchID %>
</p>

<p>
  <strong>Ifindex:</strong>
  <%= @trafficdatum.ifIndex %>
</p>

<p>
  <strong>Ifdescr:</strong>
  <%= @trafficdatum.ifDescr %>
</p>

<p>
  <strong>Ifinoctets:</strong>
  <%= @trafficdatum.ifInOctets %>
</p>

<p>
  <strong>Ifoutoctets:</strong>
  <%= @trafficdatum.ifOutOctets %>
</p>

<p>
  <strong>Diffinoctets:</strong>
  <%= @trafficdatum.diffInOctets %>
</p>

<p>
  <strong>Diffoutoctets:</strong>
  <%= @trafficdatum.diffOutOctets %>
</p>

<%= link_to 'Edit', edit_trafficdatum_path(@trafficdatum) %> |
<%= link_to 'Back', trafficdata_path %>